### ISSUE TITLE
v2.2.4 tarball contains 1.2MB gif

### ISSUE THREAD

**Issue by stefanpenner** [socketio/socket.io-parser#30] opened 2015-08-11 17:33 UTC
```sh
wget (npm info --json socket.io-parser | jq -r '.dist.tarball')
tar --extract --file=socket.io-parser-2.2.4.tgz package/bg.gif
file package/bg.gif
$> package/bg.gif: GIF image data, version 89a, 640 x 420
du -sh package/bg.gif
$> 1.2M	package/bg.gif
```

It does not appear like this is part of the repo, so maybe this a accidentally included file during packaging.

**Comment by nuclearace** [comment] 2015-08-11 17:40
Duplicate of #26

**Closed by nuclearace** 2015-08-11 17:40 UTC
